### ISSUE TITLE
https://github.com/CESSProject/doc-v2-cn/blob/main/ref/storage/identification.md

### ISSUE THREAD

**Issue by Kkketh** [CESSProject/doc-v2-cn#67]
这里的省略是预期的吗？
<img width="503" alt="截屏2023-11-03 下午4 20 16" src="https://github.com/CESSProject/doc-v2-cn/assets/142964628/4e435e90-4cdd-4c92-9ef7-b79808708f3a">

**Comment by jimmychu0807** [comment]
我最後決定把它省略了，好像好看一點
